server:
  port: 8078
  servlet:
    context-path: /auth-center
spring:
  datasource:
    username: root
    password: 200225
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gedk?serverTimezone=GMT%2B8
  redis:
    host: localhost
    port: 6379
    password: 200225