server:
  servlet:
    context-path: /order-service
  port: 8099
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gedk?useSSL=false
    username: root
    password: 200225
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order-service
  rabbitmq:
    host: 192.168.1.4
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        myInput1:
          destination: gedk
          group: x
        myInput2:
          destination: gedk
          group: y
        myOutput:
          destination: gedk

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: order-service